"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.bank_transfer_direction import BankTransferDirection
from openapi_client.model.bank_transfer_failure import BankTransferFailure
from openapi_client.model.bank_transfer_metadata import BankTransferMetadata
from openapi_client.model.bank_transfer_network import BankTransferNetwork
from openapi_client.model.bank_transfer_status import BankTransferStatus
from openapi_client.model.bank_transfer_type import BankTransferType
from openapi_client.model.bank_transfer_user import BankTransferUser
globals()['ACHClass'] = ACHClass
globals()['BankTransferDirection'] = BankTransferDirection
globals()['BankTransferFailure'] = BankTransferFailure
globals()['BankTransferMetadata'] = BankTransferMetadata
globals()['BankTransferNetwork'] = BankTransferNetwork
globals()['BankTransferStatus'] = BankTransferStatus
globals()['BankTransferType'] = BankTransferType
globals()['BankTransferUser'] = BankTransferUser
from openapi_client.model.bank_transfer import BankTransfer


class TestBankTransfer(unittest.TestCase):
    """BankTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankTransfer(self):
        """Test BankTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
