"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mortgage_interest_rate import MortgageInterestRate
from openapi_client.model.mortgage_property_address import MortgagePropertyAddress
globals()['MortgageInterestRate'] = MortgageInterestRate
globals()['MortgagePropertyAddress'] = MortgagePropertyAddress
from openapi_client.model.mortgage_liability import MortgageLiability


class TestMortgageLiability(unittest.TestCase):
    """MortgageLiability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMortgageLiability(self):
        """Test MortgageLiability"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MortgageLiability()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
