"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.investment_holdings_get_request_options import InvestmentHoldingsGetRequestOptions
globals()['InvestmentHoldingsGetRequestOptions'] = InvestmentHoldingsGetRequestOptions
from openapi_client.model.investments_holdings_get_request import InvestmentsHoldingsGetRequest


class TestInvestmentsHoldingsGetRequest(unittest.TestCase):
    """InvestmentsHoldingsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestmentsHoldingsGetRequest(self):
        """Test InvestmentsHoldingsGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvestmentsHoldingsGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
