"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.transactions_recurring_get_request import TransactionsRecurringGetRequest


class TestTransactionsRecurringGetRequest(unittest.TestCase):
    """TransactionsRecurringGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionsRecurringGetRequest(self):
        """Test TransactionsRecurringGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionsRecurringGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
