"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.credit_card_liability import CreditCardLiability
from openapi_client.model.mortgage_liability import MortgageLiability
from openapi_client.model.student_loan import StudentLoan
globals()['CreditCardLiability'] = CreditCardLiability
globals()['MortgageLiability'] = MortgageLiability
globals()['StudentLoan'] = StudentLoan
from openapi_client.model.liabilities_object import LiabilitiesObject


class TestLiabilitiesObject(unittest.TestCase):
    """LiabilitiesObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiabilitiesObject(self):
        """Test LiabilitiesObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiabilitiesObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
