"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.numbers_bacs import NumbersBACS
globals()['NumbersBACS'] = NumbersBACS
from openapi_client.model.numbers_bacs_nullable import NumbersBACSNullable


class TestNumbersBACSNullable(unittest.TestCase):
    """NumbersBACSNullable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumbersBACSNullable(self):
        """Test NumbersBACSNullable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NumbersBACSNullable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
