"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.deposit_switch_create_request_options import DepositSwitchCreateRequestOptions
from openapi_client.model.deposit_switch_target_account import DepositSwitchTargetAccount
from openapi_client.model.deposit_switch_target_user import DepositSwitchTargetUser
globals()['DepositSwitchCreateRequestOptions'] = DepositSwitchCreateRequestOptions
globals()['DepositSwitchTargetAccount'] = DepositSwitchTargetAccount
globals()['DepositSwitchTargetUser'] = DepositSwitchTargetUser
from openapi_client.model.deposit_switch_alt_create_request import DepositSwitchAltCreateRequest


class TestDepositSwitchAltCreateRequest(unittest.TestCase):
    """DepositSwitchAltCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepositSwitchAltCreateRequest(self):
        """Test DepositSwitchAltCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DepositSwitchAltCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
