"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_initiation_recipient import PaymentInitiationRecipient
globals()['PaymentInitiationRecipient'] = PaymentInitiationRecipient
from openapi_client.model.payment_initiation_recipient_list_response import PaymentInitiationRecipientListResponse


class TestPaymentInitiationRecipientListResponse(unittest.TestCase):
    """PaymentInitiationRecipientListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentInitiationRecipientListResponse(self):
        """Test PaymentInitiationRecipientListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentInitiationRecipientListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
