"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.numbers_ach_nullable import NumbersACHNullable
from openapi_client.model.numbers_bacs_nullable import NumbersBACSNullable
from openapi_client.model.numbers_eft_nullable import NumbersEFTNullable
from openapi_client.model.numbers_international_nullable import NumbersInternationalNullable
globals()['NumbersACHNullable'] = NumbersACHNullable
globals()['NumbersBACSNullable'] = NumbersBACSNullable
globals()['NumbersEFTNullable'] = NumbersEFTNullable
globals()['NumbersInternationalNullable'] = NumbersInternationalNullable
from openapi_client.model.processor_number import ProcessorNumber


class TestProcessorNumber(unittest.TestCase):
    """ProcessorNumber unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorNumber(self):
        """Test ProcessorNumber"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorNumber()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
