"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.country_code import CountryCode
from openapi_client.model.institutions_search_request_options import InstitutionsSearchRequestOptions
from openapi_client.model.products import Products
globals()['CountryCode'] = CountryCode
globals()['InstitutionsSearchRequestOptions'] = InstitutionsSearchRequestOptions
globals()['Products'] = Products
from openapi_client.model.institutions_search_request import InstitutionsSearchRequest


class TestInstitutionsSearchRequest(unittest.TestCase):
    """InstitutionsSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionsSearchRequest(self):
        """Test InstitutionsSearchRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstitutionsSearchRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
