"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_filter import AccountFilter
from openapi_client.model.account_selection_cardinality import AccountSelectionCardinality
globals()['AccountFilter'] = AccountFilter
globals()['AccountSelectionCardinality'] = AccountSelectionCardinality
from openapi_client.model.requested_scopes import RequestedScopes


class TestRequestedScopes(unittest.TestCase):
    """RequestedScopes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestedScopes(self):
        """Test RequestedScopes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestedScopes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
