"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_status_investments import ItemStatusInvestments
from openapi_client.model.item_status_last_webhook import ItemStatusLastWebhook
from openapi_client.model.item_status_transactions import ItemStatusTransactions
globals()['ItemStatusInvestments'] = ItemStatusInvestments
globals()['ItemStatusLastWebhook'] = ItemStatusLastWebhook
globals()['ItemStatusTransactions'] = ItemStatusTransactions
from openapi_client.model.item_status import ItemStatus


class TestItemStatus(unittest.TestCase):
    """ItemStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemStatus(self):
        """Test ItemStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
