"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wallet_transaction_amount import WalletTransactionAmount
from openapi_client.model.wallet_transaction_counterparty import WalletTransactionCounterparty
from openapi_client.model.wallet_transaction_idempotency_key import WalletTransactionIdempotencyKey
globals()['WalletTransactionAmount'] = WalletTransactionAmount
globals()['WalletTransactionCounterparty'] = WalletTransactionCounterparty
globals()['WalletTransactionIdempotencyKey'] = WalletTransactionIdempotencyKey
from openapi_client.model.wallet_transaction_execute_request import WalletTransactionExecuteRequest


class TestWalletTransactionExecuteRequest(unittest.TestCase):
    """WalletTransactionExecuteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransactionExecuteRequest(self):
        """Test WalletTransactionExecuteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletTransactionExecuteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
