"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.accounts_balance_get_request_options import AccountsBalanceGetRequestOptions
globals()['AccountsBalanceGetRequestOptions'] = AccountsBalanceGetRequestOptions
from openapi_client.model.accounts_balance_get_request import AccountsBalanceGetRequest


class TestAccountsBalanceGetRequest(unittest.TestCase):
    """AccountsBalanceGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsBalanceGetRequest(self):
        """Test AccountsBalanceGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountsBalanceGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
