"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.accounts_get_request_options import AccountsGetRequestOptions
globals()['AccountsGetRequestOptions'] = AccountsGetRequestOptions
from openapi_client.model.accounts_get_request import AccountsGetRequest


class TestAccountsGetRequest(unittest.TestCase):
    """AccountsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsGetRequest(self):
        """Test AccountsGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountsGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
