"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.w2_box12 import W2Box12


class TestW2Box12(unittest.TestCase):
    """W2Box12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testW2Box12(self):
        """Test W2Box12"""
        # FIXME: construct object with mandatory attributes with example values
        # model = W2Box12()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
