"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mfa import MFA
from openapi_client.model.override_accounts import OverrideAccounts
globals()['MFA'] = MFA
globals()['OverrideAccounts'] = OverrideAccounts
from openapi_client.model.user_custom_password import UserCustomPassword


class TestUserCustomPassword(unittest.TestCase):
    """UserCustomPassword unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserCustomPassword(self):
        """Test UserCustomPassword"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserCustomPassword()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
