"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.item_import_request_options import ItemImportRequestOptions
from openapi_client.model.item_import_request_user_auth import ItemImportRequestUserAuth
from openapi_client.model.products import Products
globals()['ItemImportRequestOptions'] = ItemImportRequestOptions
globals()['ItemImportRequestUserAuth'] = ItemImportRequestUserAuth
globals()['Products'] = Products
from openapi_client.model.item_import_request import ItemImportRequest


class TestItemImportRequest(unittest.TestCase):
    """ItemImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemImportRequest(self):
        """Test ItemImportRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemImportRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
