"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.depository_account_subtypes import DepositoryAccountSubtypes
globals()['DepositoryAccountSubtypes'] = DepositoryAccountSubtypes
from openapi_client.model.depository_filter import DepositoryFilter


class TestDepositoryFilter(unittest.TestCase):
    """DepositoryFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDepositoryFilter(self):
        """Test DepositoryFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DepositoryFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
