"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.link_token_create_credit_filter import LinkTokenCreateCreditFilter
from openapi_client.model.link_token_create_depository_filter import LinkTokenCreateDepositoryFilter
from openapi_client.model.link_token_create_investment_filter import LinkTokenCreateInvestmentFilter
from openapi_client.model.link_token_create_loan_filter import LinkTokenCreateLoanFilter
globals()['LinkTokenCreateCreditFilter'] = LinkTokenCreateCreditFilter
globals()['LinkTokenCreateDepositoryFilter'] = LinkTokenCreateDepositoryFilter
globals()['LinkTokenCreateInvestmentFilter'] = LinkTokenCreateInvestmentFilter
globals()['LinkTokenCreateLoanFilter'] = LinkTokenCreateLoanFilter
from openapi_client.model.link_token_create_request_account_subtypes import LinkTokenCreateRequestAccountSubtypes


class TestLinkTokenCreateRequestAccountSubtypes(unittest.TestCase):
    """LinkTokenCreateRequestAccountSubtypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkTokenCreateRequestAccountSubtypes(self):
        """Test LinkTokenCreateRequestAccountSubtypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LinkTokenCreateRequestAccountSubtypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
