"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.country_code import CountryCode
from openapi_client.model.institutions_get_request_options import InstitutionsGetRequestOptions
globals()['CountryCode'] = CountryCode
globals()['InstitutionsGetRequestOptions'] = InstitutionsGetRequestOptions
from openapi_client.model.institutions_get_request import InstitutionsGetRequest


class TestInstitutionsGetRequest(unittest.TestCase):
    """InstitutionsGetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionsGetRequest(self):
        """Test InstitutionsGetRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstitutionsGetRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
