"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.asset_report_transaction_all_of import AssetReportTransactionAllOf
from openapi_client.model.location import Location
from openapi_client.model.payment_meta import PaymentMeta
from openapi_client.model.transaction_base import TransactionBase
globals()['AssetReportTransactionAllOf'] = AssetReportTransactionAllOf
globals()['Location'] = Location
globals()['PaymentMeta'] = PaymentMeta
globals()['TransactionBase'] = TransactionBase
from openapi_client.model.asset_report_transaction import AssetReportTransaction


class TestAssetReportTransaction(unittest.TestCase):
    """AssetReportTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetReportTransaction(self):
        """Test AssetReportTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetReportTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
