"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.numbers_ach import NumbersACH
from openapi_client.model.numbers_bacs import NumbersBACS
from openapi_client.model.numbers_eft import NumbersEFT
from openapi_client.model.numbers_international import NumbersInternational
globals()['NumbersACH'] = NumbersACH
globals()['NumbersBACS'] = NumbersBACS
globals()['NumbersEFT'] = NumbersEFT
globals()['NumbersInternational'] = NumbersInternational
from openapi_client.model.auth_get_numbers import AuthGetNumbers


class TestAuthGetNumbers(unittest.TestCase):
    """AuthGetNumbers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAuthGetNumbers(self):
        """Test AuthGetNumbers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AuthGetNumbers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
