"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recurring_transaction_frequency import RecurringTransactionFrequency
from openapi_client.model.transaction_stream_amount import TransactionStreamAmount
globals()['RecurringTransactionFrequency'] = RecurringTransactionFrequency
globals()['TransactionStreamAmount'] = TransactionStreamAmount
from openapi_client.model.transaction_stream import TransactionStream


class TestTransactionStream(unittest.TestCase):
    """TransactionStream unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStream(self):
        """Test TransactionStream"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionStream()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
