"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_metadata import DocumentMetadata
from openapi_client.model.paystub import Paystub
from openapi_client.model.plaid_error import PlaidError
globals()['DocumentMetadata'] = DocumentMetadata
globals()['Paystub'] = Paystub
globals()['PlaidError'] = PlaidError
from openapi_client.model.income_verification_paystubs_get_response import IncomeVerificationPaystubsGetResponse


class TestIncomeVerificationPaystubsGetResponse(unittest.TestCase):
    """IncomeVerificationPaystubsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomeVerificationPaystubsGetResponse(self):
        """Test IncomeVerificationPaystubsGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncomeVerificationPaystubsGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
