"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.connected_application import ConnectedApplication
globals()['ConnectedApplication'] = ConnectedApplication
from openapi_client.model.item_application_list_response import ItemApplicationListResponse


class TestItemApplicationListResponse(unittest.TestCase):
    """ItemApplicationListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemApplicationListResponse(self):
        """Test ItemApplicationListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemApplicationListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
