"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.external_payment_options import ExternalPaymentOptions
from openapi_client.model.external_payment_schedule_request import ExternalPaymentScheduleRequest
from openapi_client.model.payment_amount import PaymentAmount
globals()['ExternalPaymentOptions'] = ExternalPaymentOptions
globals()['ExternalPaymentScheduleRequest'] = ExternalPaymentScheduleRequest
globals()['PaymentAmount'] = PaymentAmount
from openapi_client.model.payment_initiation_payment_create_request import PaymentInitiationPaymentCreateRequest


class TestPaymentInitiationPaymentCreateRequest(unittest.TestCase):
    """PaymentInitiationPaymentCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentInitiationPaymentCreateRequest(self):
        """Test PaymentInitiationPaymentCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentInitiationPaymentCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
