"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.doc_type import DocType


class TestDocType(unittest.TestCase):
    """DocType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocType(self):
        """Test DocType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
