"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pslf_status import PSLFStatus
from openapi_client.model.servicer_address_data import ServicerAddressData
from openapi_client.model.student_loan_status import StudentLoanStatus
from openapi_client.model.student_repayment_plan import StudentRepaymentPlan
globals()['PSLFStatus'] = PSLFStatus
globals()['ServicerAddressData'] = ServicerAddressData
globals()['StudentLoanStatus'] = StudentLoanStatus
globals()['StudentRepaymentPlan'] = StudentRepaymentPlan
from openapi_client.model.student_loan import StudentLoan


class TestStudentLoan(unittest.TestCase):
    """StudentLoan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentLoan(self):
        """Test StudentLoan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudentLoan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
