"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.scopes import Scopes
from openapi_client.model.scopes_context import ScopesContext
globals()['Scopes'] = Scopes
globals()['ScopesContext'] = ScopesContext
from openapi_client.model.item_application_scopes_update_request import ItemApplicationScopesUpdateRequest


class TestItemApplicationScopesUpdateRequest(unittest.TestCase):
    """ItemApplicationScopesUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemApplicationScopesUpdateRequest(self):
        """Test ItemApplicationScopesUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemApplicationScopesUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
