"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.bank_transfer_idempotency_key import BankTransferIdempotencyKey
from openapi_client.model.bank_transfer_metadata import BankTransferMetadata
from openapi_client.model.bank_transfer_network import BankTransferNetwork
from openapi_client.model.bank_transfer_type import BankTransferType
from openapi_client.model.bank_transfer_user import BankTransferUser
globals()['ACHClass'] = ACHClass
globals()['BankTransferIdempotencyKey'] = BankTransferIdempotencyKey
globals()['BankTransferMetadata'] = BankTransferMetadata
globals()['BankTransferNetwork'] = BankTransferNetwork
globals()['BankTransferType'] = BankTransferType
globals()['BankTransferUser'] = BankTransferUser
from openapi_client.model.bank_transfer_create_request import BankTransferCreateRequest


class TestBankTransferCreateRequest(unittest.TestCase):
    """BankTransferCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankTransferCreateRequest(self):
        """Test BankTransferCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankTransferCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
