"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.signal_evaluate_core_attributes import SignalEvaluateCoreAttributes
from openapi_client.model.signal_scores import SignalScores
globals()['SignalEvaluateCoreAttributes'] = SignalEvaluateCoreAttributes
globals()['SignalScores'] = SignalScores
from openapi_client.model.signal_evaluate_response import SignalEvaluateResponse


class TestSignalEvaluateResponse(unittest.TestCase):
    """SignalEvaluateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalEvaluateResponse(self):
        """Test SignalEvaluateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignalEvaluateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
