"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.removed_transaction import RemovedTransaction
from openapi_client.model.transaction import Transaction
globals()['RemovedTransaction'] = RemovedTransaction
globals()['Transaction'] = Transaction
from openapi_client.model.transactions_sync_response import TransactionsSyncResponse


class TestTransactionsSyncResponse(unittest.TestCase):
    """TransactionsSyncResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionsSyncResponse(self):
        """Test TransactionsSyncResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionsSyncResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
