"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.pay import Pay
from openapi_client.model.total_canonical_description import TotalCanonicalDescription
globals()['Pay'] = Pay
globals()['TotalCanonicalDescription'] = TotalCanonicalDescription
from openapi_client.model.total import Total


class TestTotal(unittest.TestCase):
    """Total unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTotal(self):
        """Test Total"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Total()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
