"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.doc_type import DocType
globals()['DocType'] = DocType
from openapi_client.model.document_metadata import DocumentMetadata


class TestDocumentMetadata(unittest.TestCase):
    """DocumentMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentMetadata(self):
        """Test DocumentMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocumentMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
