"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.credit_filter import CreditFilter
from openapi_client.model.depository_filter import DepositoryFilter
from openapi_client.model.investment_filter import InvestmentFilter
from openapi_client.model.loan_filter import LoanFilter
globals()['CreditFilter'] = CreditFilter
globals()['DepositoryFilter'] = DepositoryFilter
globals()['InvestmentFilter'] = InvestmentFilter
globals()['LoanFilter'] = LoanFilter
from openapi_client.model.account_filters_response import AccountFiltersResponse


class TestAccountFiltersResponse(unittest.TestCase):
    """AccountFiltersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountFiltersResponse(self):
        """Test AccountFiltersResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountFiltersResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
