"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bank_initiated_return_risk import BankInitiatedReturnRisk
from openapi_client.model.customer_initiated_return_risk import CustomerInitiatedReturnRisk
globals()['BankInitiatedReturnRisk'] = BankInitiatedReturnRisk
globals()['CustomerInitiatedReturnRisk'] = CustomerInitiatedReturnRisk
from openapi_client.model.signal_scores import SignalScores


class TestSignalScores(unittest.TestCase):
    """SignalScores unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalScores(self):
        """Test SignalScores"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignalScores()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
