"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_base import AccountBase
from openapi_client.model.processor_number import ProcessorNumber
globals()['AccountBase'] = AccountBase
globals()['ProcessorNumber'] = ProcessorNumber
from openapi_client.model.processor_auth_get_response import ProcessorAuthGetResponse


class TestProcessorAuthGetResponse(unittest.TestCase):
    """ProcessorAuthGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorAuthGetResponse(self):
        """Test ProcessorAuthGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorAuthGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
