"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.transfer_authorization_device import TransferAuthorizationDevice
from openapi_client.model.transfer_network import TransferNetwork
from openapi_client.model.transfer_type import TransferType
from openapi_client.model.transfer_user_in_request import TransferUserInRequest
globals()['ACHClass'] = ACHClass
globals()['TransferAuthorizationDevice'] = TransferAuthorizationDevice
globals()['TransferNetwork'] = TransferNetwork
globals()['TransferType'] = TransferType
globals()['TransferUserInRequest'] = TransferUserInRequest
from openapi_client.model.transfer_authorization_create_request import TransferAuthorizationCreateRequest


class TestTransferAuthorizationCreateRequest(unittest.TestCase):
    """TransferAuthorizationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransferAuthorizationCreateRequest(self):
        """Test TransferAuthorizationCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransferAuthorizationCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
