"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.transfer_authorization_guarantee_decision import TransferAuthorizationGuaranteeDecision
from openapi_client.model.transfer_authorization_guarantee_decision_rationale import TransferAuthorizationGuaranteeDecisionRationale
from openapi_client.model.transfer_failure import TransferFailure
from openapi_client.model.transfer_metadata import TransferMetadata
from openapi_client.model.transfer_network import TransferNetwork
from openapi_client.model.transfer_status import TransferStatus
from openapi_client.model.transfer_sweep_status import TransferSweepStatus
from openapi_client.model.transfer_type import TransferType
from openapi_client.model.transfer_user_in_response import TransferUserInResponse
globals()['ACHClass'] = ACHClass
globals()['TransferAuthorizationGuaranteeDecision'] = TransferAuthorizationGuaranteeDecision
globals()['TransferAuthorizationGuaranteeDecisionRationale'] = TransferAuthorizationGuaranteeDecisionRationale
globals()['TransferFailure'] = TransferFailure
globals()['TransferMetadata'] = TransferMetadata
globals()['TransferNetwork'] = TransferNetwork
globals()['TransferStatus'] = TransferStatus
globals()['TransferSweepStatus'] = TransferSweepStatus
globals()['TransferType'] = TransferType
globals()['TransferUserInResponse'] = TransferUserInResponse
from openapi_client.model.transfer import Transfer


class TestTransfer(unittest.TestCase):
    """Transfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransfer(self):
        """Test Transfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Transfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
