"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wallet_transaction import WalletTransaction
globals()['WalletTransaction'] = WalletTransaction
from openapi_client.model.wallet_transactions_list_response import WalletTransactionsListResponse


class TestWalletTransactionsListResponse(unittest.TestCase):
    """WalletTransactionsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransactionsListResponse(self):
        """Test WalletTransactionsListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletTransactionsListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
