"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.liabilities_account_ids_with_updated_liabilities import LiabilitiesAccountIdsWithUpdatedLiabilities


class TestLiabilitiesAccountIdsWithUpdatedLiabilities(unittest.TestCase):
    """LiabilitiesAccountIdsWithUpdatedLiabilities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiabilitiesAccountIdsWithUpdatedLiabilities(self):
        """Test LiabilitiesAccountIdsWithUpdatedLiabilities"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiabilitiesAccountIdsWithUpdatedLiabilities()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
