"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_initiation_optional_restriction_bacs import PaymentInitiationOptionalRestrictionBacs
from openapi_client.model.payment_scheme import PaymentScheme
globals()['PaymentInitiationOptionalRestrictionBacs'] = PaymentInitiationOptionalRestrictionBacs
globals()['PaymentScheme'] = PaymentScheme
from openapi_client.model.external_payment_options import ExternalPaymentOptions


class TestExternalPaymentOptions(unittest.TestCase):
    """ExternalPaymentOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalPaymentOptions(self):
        """Test ExternalPaymentOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalPaymentOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
