"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.payment_initiation_maximum_payment_amount import PaymentInitiationMaximumPaymentAmount
from openapi_client.model.payment_initiation_standing_order_metadata import PaymentInitiationStandingOrderMetadata
globals()['PaymentInitiationMaximumPaymentAmount'] = PaymentInitiationMaximumPaymentAmount
globals()['PaymentInitiationStandingOrderMetadata'] = PaymentInitiationStandingOrderMetadata
from openapi_client.model.payment_initiation_metadata import PaymentInitiationMetadata


class TestPaymentInitiationMetadata(unittest.TestCase):
    """PaymentInitiationMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentInitiationMetadata(self):
        """Test PaymentInitiationMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaymentInitiationMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
