"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.plaid_error import PlaidError
globals()['PlaidError'] = PlaidError
from openapi_client.model.historical_update_webhook import HistoricalUpdateWebhook


class TestHistoricalUpdateWebhook(unittest.TestCase):
    """HistoricalUpdateWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHistoricalUpdateWebhook(self):
        """Test HistoricalUpdateWebhook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HistoricalUpdateWebhook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
