"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wallet_transaction_amount import WalletTransactionAmount
from openapi_client.model.wallet_transaction_counterparty import WalletTransactionCounterparty
from openapi_client.model.wallet_transaction_status import WalletTransactionStatus
globals()['WalletTransactionAmount'] = WalletTransactionAmount
globals()['WalletTransactionCounterparty'] = WalletTransactionCounterparty
globals()['WalletTransactionStatus'] = WalletTransactionStatus
from openapi_client.model.wallet_transaction import WalletTransaction


class TestWalletTransaction(unittest.TestCase):
    """WalletTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransaction(self):
        """Test WalletTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
