"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_identity import AccountIdentity
from openapi_client.model.item import Item
globals()['AccountIdentity'] = AccountIdentity
globals()['Item'] = Item
from openapi_client.model.identity_get_response import IdentityGetResponse


class TestIdentityGetResponse(unittest.TestCase):
    """IdentityGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityGetResponse(self):
        """Test IdentityGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IdentityGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
