"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.plaid_error import PlaidError
globals()['PlaidError'] = PlaidError
from openapi_client.model.default_update_webhook import DefaultUpdateWebhook


class TestDefaultUpdateWebhook(unittest.TestCase):
    """DefaultUpdateWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDefaultUpdateWebhook(self):
        """Test DefaultUpdateWebhook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DefaultUpdateWebhook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
