"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.auth_metadata import AuthMetadata
from openapi_client.model.country_code import CountryCode
from openapi_client.model.institution_status import InstitutionStatus
from openapi_client.model.payment_initiation_metadata import PaymentInitiationMetadata
from openapi_client.model.products import Products
globals()['AuthMetadata'] = AuthMetadata
globals()['CountryCode'] = CountryCode
globals()['InstitutionStatus'] = InstitutionStatus
globals()['PaymentInitiationMetadata'] = PaymentInitiationMetadata
globals()['Products'] = Products
from openapi_client.model.institution import Institution


class TestInstitution(unittest.TestCase):
    """Institution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitution(self):
        """Test Institution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Institution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
