"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_subtype import AccountSubtype
from openapi_client.model.holdings_override import HoldingsOverride
from openapi_client.model.income_override import IncomeOverride
from openapi_client.model.inflow_model import InflowModel
from openapi_client.model.investments_transactions_override import InvestmentsTransactionsOverride
from openapi_client.model.liability_override import LiabilityOverride
from openapi_client.model.meta import Meta
from openapi_client.model.numbers import Numbers
from openapi_client.model.override_account_type import OverrideAccountType
from openapi_client.model.owner_override import OwnerOverride
from openapi_client.model.transaction_override import TransactionOverride
globals()['AccountSubtype'] = AccountSubtype
globals()['HoldingsOverride'] = HoldingsOverride
globals()['IncomeOverride'] = IncomeOverride
globals()['InflowModel'] = InflowModel
globals()['InvestmentsTransactionsOverride'] = InvestmentsTransactionsOverride
globals()['LiabilityOverride'] = LiabilityOverride
globals()['Meta'] = Meta
globals()['Numbers'] = Numbers
globals()['OverrideAccountType'] = OverrideAccountType
globals()['OwnerOverride'] = OwnerOverride
globals()['TransactionOverride'] = TransactionOverride
from openapi_client.model.override_accounts import OverrideAccounts


class TestOverrideAccounts(unittest.TestCase):
    """OverrideAccounts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOverrideAccounts(self):
        """Test OverrideAccounts"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OverrideAccounts()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
