"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.transfer_authorization_decision_rationale import TransferAuthorizationDecisionRationale
from openapi_client.model.transfer_intent_create_mode import TransferIntentCreateMode
from openapi_client.model.transfer_intent_get_failure_reason import TransferIntentGetFailureReason
from openapi_client.model.transfer_metadata import TransferMetadata
from openapi_client.model.transfer_user_in_response import TransferUserInResponse
globals()['ACHClass'] = ACHClass
globals()['TransferAuthorizationDecisionRationale'] = TransferAuthorizationDecisionRationale
globals()['TransferIntentCreateMode'] = TransferIntentCreateMode
globals()['TransferIntentGetFailureReason'] = TransferIntentGetFailureReason
globals()['TransferMetadata'] = TransferMetadata
globals()['TransferUserInResponse'] = TransferUserInResponse
from openapi_client.model.transfer_intent_get import TransferIntentGet


class TestTransferIntentGet(unittest.TestCase):
    """TransferIntentGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransferIntentGet(self):
        """Test TransferIntentGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransferIntentGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
