"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.address import Address
from openapi_client.model.pslf_status import PSLFStatus
from openapi_client.model.student_loan_repayment_model import StudentLoanRepaymentModel
from openapi_client.model.student_loan_status import StudentLoanStatus
globals()['Address'] = Address
globals()['PSLFStatus'] = PSLFStatus
globals()['StudentLoanRepaymentModel'] = StudentLoanRepaymentModel
globals()['StudentLoanStatus'] = StudentLoanStatus
from openapi_client.model.liability_override import LiabilityOverride


class TestLiabilityOverride(unittest.TestCase):
    """LiabilityOverride unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLiabilityOverride(self):
        """Test LiabilityOverride"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LiabilityOverride()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
