"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.health_incident import HealthIncident
from openapi_client.model.product_status import ProductStatus
globals()['HealthIncident'] = HealthIncident
globals()['ProductStatus'] = ProductStatus
from openapi_client.model.institution_status import InstitutionStatus


class TestInstitutionStatus(unittest.TestCase):
    """InstitutionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionStatus(self):
        """Test InstitutionStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstitutionStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
