"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.employee import Employee
from openapi_client.model.paystub_employer import PaystubEmployer
from openapi_client.model.w2_box12 import W2Box12
from openapi_client.model.w2_state_and_local_wages import W2StateAndLocalWages
globals()['Employee'] = Employee
globals()['PaystubEmployer'] = PaystubEmployer
globals()['W2Box12'] = W2Box12
globals()['W2StateAndLocalWages'] = W2StateAndLocalWages
from openapi_client.model.w2 import W2


class TestW2(unittest.TestCase):
    """W2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testW2(self):
        """Test W2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = W2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
