"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.external_payment_schedule_base import ExternalPaymentScheduleBase
from openapi_client.model.payment_schedule_interval import PaymentScheduleInterval
globals()['ExternalPaymentScheduleBase'] = ExternalPaymentScheduleBase
globals()['PaymentScheduleInterval'] = PaymentScheduleInterval
from openapi_client.model.external_payment_schedule_request import ExternalPaymentScheduleRequest


class TestExternalPaymentScheduleRequest(unittest.TestCase):
    """ExternalPaymentScheduleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalPaymentScheduleRequest(self):
        """Test ExternalPaymentScheduleRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalPaymentScheduleRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
