"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.asset_report_user import AssetReportUser
globals()['AssetReportUser'] = AssetReportUser
from openapi_client.model.asset_report_refresh_request_options import AssetReportRefreshRequestOptions


class TestAssetReportRefreshRequestOptions(unittest.TestCase):
    """AssetReportRefreshRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetReportRefreshRequestOptions(self):
        """Test AssetReportRefreshRequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetReportRefreshRequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
