"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.signal_address_data import SignalAddressData
from openapi_client.model.signal_person_name import SignalPersonName
globals()['SignalAddressData'] = SignalAddressData
globals()['SignalPersonName'] = SignalPersonName
from openapi_client.model.signal_user import SignalUser


class TestSignalUser(unittest.TestCase):
    """SignalUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignalUser(self):
        """Test SignalUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SignalUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
