"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.customer_initiated_risk_tier import CustomerInitiatedRiskTier
from openapi_client.model.signal_score import SignalScore
globals()['CustomerInitiatedRiskTier'] = CustomerInitiatedRiskTier
globals()['SignalScore'] = SignalScore
from openapi_client.model.customer_initiated_return_risk import CustomerInitiatedReturnRisk


class TestCustomerInitiatedReturnRisk(unittest.TestCase):
    """CustomerInitiatedReturnRisk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomerInitiatedReturnRisk(self):
        """Test CustomerInitiatedReturnRisk"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomerInitiatedReturnRisk()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
