"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.income_verification_precheck_confidence import IncomeVerificationPrecheckConfidence
globals()['IncomeVerificationPrecheckConfidence'] = IncomeVerificationPrecheckConfidence
from openapi_client.model.income_verification_precheck_response import IncomeVerificationPrecheckResponse


class TestIncomeVerificationPrecheckResponse(unittest.TestCase):
    """IncomeVerificationPrecheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomeVerificationPrecheckResponse(self):
        """Test IncomeVerificationPrecheckResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncomeVerificationPrecheckResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
