"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wallet_transaction_counterparty_numbers import WalletTransactionCounterpartyNumbers
globals()['WalletTransactionCounterpartyNumbers'] = WalletTransactionCounterpartyNumbers
from openapi_client.model.wallet_transaction_counterparty import WalletTransactionCounterparty


class TestWalletTransactionCounterparty(unittest.TestCase):
    """WalletTransactionCounterparty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransactionCounterparty(self):
        """Test WalletTransactionCounterparty"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletTransactionCounterparty()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
