"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ach_class import ACHClass
from openapi_client.model.transfer_create_idempotency_key import TransferCreateIdempotencyKey
from openapi_client.model.transfer_metadata import TransferMetadata
from openapi_client.model.transfer_network import TransferNetwork
from openapi_client.model.transfer_type import TransferType
from openapi_client.model.transfer_user_in_request import TransferUserInRequest
globals()['ACHClass'] = ACHClass
globals()['TransferCreateIdempotencyKey'] = TransferCreateIdempotencyKey
globals()['TransferMetadata'] = TransferMetadata
globals()['TransferNetwork'] = TransferNetwork
globals()['TransferType'] = TransferType
globals()['TransferUserInRequest'] = TransferUserInRequest
from openapi_client.model.transfer_create_request import TransferCreateRequest


class TestTransferCreateRequest(unittest.TestCase):
    """TransferCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransferCreateRequest(self):
        """Test TransferCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransferCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
