"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.document_metadata import DocumentMetadata
from openapi_client.model.plaid_error import PlaidError
from openapi_client.model.taxform import Taxform
globals()['DocumentMetadata'] = DocumentMetadata
globals()['PlaidError'] = PlaidError
globals()['Taxform'] = Taxform
from openapi_client.model.income_verification_taxforms_get_response import IncomeVerificationTaxformsGetResponse


class TestIncomeVerificationTaxformsGetResponse(unittest.TestCase):
    """IncomeVerificationTaxformsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomeVerificationTaxformsGetResponse(self):
        """Test IncomeVerificationTaxformsGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncomeVerificationTaxformsGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
