"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_base import AccountBase
from openapi_client.model.investment_transaction import InvestmentTransaction
from openapi_client.model.item import Item
from openapi_client.model.security import Security
globals()['AccountBase'] = AccountBase
globals()['InvestmentTransaction'] = InvestmentTransaction
globals()['Item'] = Item
globals()['Security'] = Security
from openapi_client.model.investments_transactions_get_response import InvestmentsTransactionsGetResponse


class TestInvestmentsTransactionsGetResponse(unittest.TestCase):
    """InvestmentsTransactionsGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvestmentsTransactionsGetResponse(self):
        """Test InvestmentsTransactionsGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InvestmentsTransactionsGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
