"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.asset_report_transaction import AssetReportTransaction
from openapi_client.model.historical_balance import HistoricalBalance
from openapi_client.model.owner import Owner
globals()['AssetReportTransaction'] = AssetReportTransaction
globals()['HistoricalBalance'] = HistoricalBalance
globals()['Owner'] = Owner
from openapi_client.model.account_assets_all_of import AccountAssetsAllOf


class TestAccountAssetsAllOf(unittest.TestCase):
    """AccountAssetsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountAssetsAllOf(self):
        """Test AccountAssetsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountAssetsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
