"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.wallet_transaction_idempotency_key import WalletTransactionIdempotencyKey


class TestWalletTransactionIdempotencyKey(unittest.TestCase):
    """WalletTransactionIdempotencyKey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWalletTransactionIdempotencyKey(self):
        """Test WalletTransactionIdempotencyKey"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WalletTransactionIdempotencyKey()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
