"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.personal_finance_category import PersonalFinanceCategory
from openapi_client.model.transaction_code import TransactionCode
globals()['PersonalFinanceCategory'] = PersonalFinanceCategory
globals()['TransactionCode'] = TransactionCode
from openapi_client.model.transaction_all_of import TransactionAllOf


class TestTransactionAllOf(unittest.TestCase):
    """TransactionAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionAllOf(self):
        """Test TransactionAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
