"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.employer_verification import EmployerVerification
from openapi_client.model.employment_verification_status import EmploymentVerificationStatus
from openapi_client.model.platform_ids import PlatformIds
globals()['EmployerVerification'] = EmployerVerification
globals()['EmploymentVerificationStatus'] = EmploymentVerificationStatus
globals()['PlatformIds'] = PlatformIds
from openapi_client.model.employment_verification import EmploymentVerification


class TestEmploymentVerification(unittest.TestCase):
    """EmploymentVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmploymentVerification(self):
        """Test EmploymentVerification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmploymentVerification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
