"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.plaid_error import PlaidError
globals()['PlaidError'] = PlaidError
from openapi_client.model.user_permission_revoked_webhook import UserPermissionRevokedWebhook


class TestUserPermissionRevokedWebhook(unittest.TestCase):
    """UserPermissionRevokedWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserPermissionRevokedWebhook(self):
        """Test UserPermissionRevokedWebhook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserPermissionRevokedWebhook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
