"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.income_verification_create_request_options import IncomeVerificationCreateRequestOptions


class TestIncomeVerificationCreateRequestOptions(unittest.TestCase):
    """IncomeVerificationCreateRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomeVerificationCreateRequestOptions(self):
        """Test IncomeVerificationCreateRequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncomeVerificationCreateRequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
