"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.institutions_search_payment_initiation_options import InstitutionsSearchPaymentInitiationOptions
globals()['InstitutionsSearchPaymentInitiationOptions'] = InstitutionsSearchPaymentInitiationOptions
from openapi_client.model.institutions_search_request_options import InstitutionsSearchRequestOptions


class TestInstitutionsSearchRequestOptions(unittest.TestCase):
    """InstitutionsSearchRequestOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstitutionsSearchRequestOptions(self):
        """Test InstitutionsSearchRequestOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstitutionsSearchRequestOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
