"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.income_verification_precheck_employer import IncomeVerificationPrecheckEmployer
from openapi_client.model.income_verification_precheck_military_info import IncomeVerificationPrecheckMilitaryInfo
from openapi_client.model.income_verification_precheck_user import IncomeVerificationPrecheckUser
from openapi_client.model.str_none_type import StrNoneType
globals()['IncomeVerificationPrecheckEmployer'] = IncomeVerificationPrecheckEmployer
globals()['IncomeVerificationPrecheckMilitaryInfo'] = IncomeVerificationPrecheckMilitaryInfo
globals()['IncomeVerificationPrecheckUser'] = IncomeVerificationPrecheckUser
globals()['str, none_type'] = str, none_type
from openapi_client.model.income_verification_precheck_request import IncomeVerificationPrecheckRequest


class TestIncomeVerificationPrecheckRequest(unittest.TestCase):
    """IncomeVerificationPrecheckRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIncomeVerificationPrecheckRequest(self):
        """Test IncomeVerificationPrecheckRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = IncomeVerificationPrecheckRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
