"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.incident_update import IncidentUpdate
globals()['IncidentUpdate'] = IncidentUpdate
from openapi_client.model.health_incident import HealthIncident


class TestHealthIncident(unittest.TestCase):
    """HealthIncident unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHealthIncident(self):
        """Test HealthIncident"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HealthIncident()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
