"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recipient_bacs_nullable import RecipientBACSNullable
globals()['RecipientBACSNullable'] = RecipientBACSNullable
from openapi_client.model.external_payment_refund_details import ExternalPaymentRefundDetails


class TestExternalPaymentRefundDetails(unittest.TestCase):
    """ExternalPaymentRefundDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalPaymentRefundDetails(self):
        """Test ExternalPaymentRefundDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExternalPaymentRefundDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
