"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_base import AccountBase
globals()['AccountBase'] = AccountBase
from openapi_client.model.processor_balance_get_response import ProcessorBalanceGetResponse


class TestProcessorBalanceGetResponse(unittest.TestCase):
    """ProcessorBalanceGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProcessorBalanceGetResponse(self):
        """Test ProcessorBalanceGetResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ProcessorBalanceGetResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
