"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.products import Products
from openapi_client.model.sandbox_public_token_create_request_options import SandboxPublicTokenCreateRequestOptions
globals()['Products'] = Products
globals()['SandboxPublicTokenCreateRequestOptions'] = SandboxPublicTokenCreateRequestOptions
from openapi_client.model.sandbox_public_token_create_request import SandboxPublicTokenCreateRequest


class TestSandboxPublicTokenCreateRequest(unittest.TestCase):
    """SandboxPublicTokenCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSandboxPublicTokenCreateRequest(self):
        """Test SandboxPublicTokenCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SandboxPublicTokenCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
