"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.simulated_transfer_sweep import SimulatedTransferSweep
globals()['SimulatedTransferSweep'] = SimulatedTransferSweep
from openapi_client.model.sandbox_transfer_sweep_simulate_response import SandboxTransferSweepSimulateResponse


class TestSandboxTransferSweepSimulateResponse(unittest.TestCase):
    """SandboxTransferSweepSimulateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSandboxTransferSweepSimulateResponse(self):
        """Test SandboxTransferSweepSimulateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SandboxTransferSweepSimulateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
