"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.bank_transfer_direction import BankTransferDirection


class TestBankTransferDirection(unittest.TestCase):
    """BankTransferDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankTransferDirection(self):
        """Test BankTransferDirection"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BankTransferDirection()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
