"""
    The Plaid API

    The Plaid REST API. Please see https://plaid.com/docs/api for more details.  # noqa: E501

    The version of the OpenAPI document: 2020-09-14_1.64.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.account_filters_response import AccountFiltersResponse
from openapi_client.model.country_code import CountryCode
from openapi_client.model.products import Products
globals()['AccountFiltersResponse'] = AccountFiltersResponse
globals()['CountryCode'] = CountryCode
globals()['Products'] = Products
from openapi_client.model.link_token_get_metadata_response import LinkTokenGetMetadataResponse


class TestLinkTokenGetMetadataResponse(unittest.TestCase):
    """LinkTokenGetMetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkTokenGetMetadataResponse(self):
        """Test LinkTokenGetMetadataResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LinkTokenGetMetadataResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
